name: 'slack post action'
description: 'Post to Slack'
branding:
  icon: 'bell'
  color: 'white'
inputs:
  channel:
    description: 'channel'
    required: true
  message:
    description: 'message'
    required: false
  user_name:
    description: 'user name'
    required: false
  user_icon:
    description: 'user icon'
    required: false
  color:
    description: 'color'
    required: false
  author_name:
    description: 'author name'
    required: false
  author_link:
    description: 'author link'
    required: false
  author_icon:
    description: 'author icon'
    required: false
  title:
    description: 'title'
    required: false
  title_link:
    description: 'title link'
    required: false
  body:
    description: 'body'
    required: false
  fields:
    description: 'fields'
    required: false
  image:
    description: 'image'
    required: false
  thumbnail:
    description: 'thumbnail'
    required: false
  footer:
    description: 'footer'
    required: false
  footer_icon:
    description: 'footer icon'
    required: false
  actions:
    description: 'actions'
    required: false
outputs:
  result:
    description: 'result'
runs:
  using: 'node12'
  main: 'dist/index.js'
